[package]
edition.workspace = true
license.workspace = true
name = "rexux-agent-extension"
version.workspace = true

[lib]
name = "rexux_agent_extension"
path = "src/lib.rs"
doctest = false
test = false

[lints]
workspace = true

[dependencies]
rexux-core = { workspace = true }
rexux-protocol = { workspace = true }

[dev-dependencies]
anyhow = { workspace = true }
core_test_support = { workspace = true }
pretty_assertions = { workspace = true }
tokio = { workspace = true, features = ["macros", "rt-multi-thread"] }
