[package]
edition.workspace = true
license.workspace = true
name = "rexux-utils-output-truncation"
version.workspace = true

[lints]
workspace = true

[dependencies]
rexux-protocol = { workspace = true }
rexux-utils-string = { workspace = true }

[dev-dependencies]
pretty_assertions = { workspace = true }

[lib]
doctest = false
