[package]
edition.workspace = true
license.workspace = true
name = "rexux-plugin"
version.workspace = true

[lib]
doctest = false
name = "rexux_plugin"
path = "src/lib.rs"

[lints]
workspace = true

[dependencies]
rexux-config = { workspace = true }
rexux-protocol = { workspace = true }
rexux-utils-absolute-path = { workspace = true }
rexux-utils-path-uri = { workspace = true }
rexux-utils-plugins = { workspace = true }
serde_json = { workspace = true }
thiserror = { workspace = true }

[dev-dependencies]
pretty_assertions = { workspace = true }
