[package]
name = "rexux-mcp-server"
version.workspace = true
edition.workspace = true
license.workspace = true

[[bin]]
name = "rexux-mcp-server"
path = "src/main.rs"

[lib]
name = "rexux_mcp_server"
path = "src/lib.rs"
doctest = false

[lints]
workspace = true

[dependencies]
anyhow = { workspace = true }
rexux-arg0 = { workspace = true }
rexux-config = { workspace = true }
rexux-core = { workspace = true }
rexux-home = { workspace = true }
rexux-image-generation-extension = { workspace = true }
rexux-exec-server = { workspace = true }
rexux-extension-api = { workspace = true }
rexux-features = { workspace = true }
rexux-git-attribution = { workspace = true }
rexux-login = { workspace = true }
rexux-otel = { workspace = true }
rexux-protocol = { workspace = true }
rexux-skills-extension = { workspace = true }
rexux-utils-cli = { workspace = true }
rexux-utils-json-to-toml = { workspace = true }
rmcp = { workspace = true }
schemars = { workspace = true }
serde = { workspace = true, features = ["derive"] }
serde_json = { workspace = true }
shlex = { workspace = true }
tokio = { workspace = true, features = [
    "io-std",
    "macros",
    "process",
    "rt-multi-thread",
    "signal",
] }
tracing = { workspace = true, features = ["log"] }
tracing-subscriber = { workspace = true, features = ["env-filter", "fmt"] }

[dev-dependencies]
app_test_support = { workspace = true }
rexux-utils-absolute-path = { workspace = true }
rexux-shell-command = { workspace = true }
core_test_support = { workspace = true }
mcp_test_support = { workspace = true }
os_info = { workspace = true }
pretty_assertions = { workspace = true }
tempfile = { workspace = true }
wiremock = { workspace = true }
